
logging:
  level:
    org.springframework.security: DEBUG
    com.netflix.discovery: 'OFF'




spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false # dates becomes 64bit integers in json otherwise

security: # Spring Boot 1.2 uses 'spring' config prefix. Spring Boot 1.3 uses 'security'
  oauth2:
    resource:
      token-type: 'Hejsan'
      tokenType: 'Hejsan'
      jwt:
        keyValue: |
         -----BEGIN PUBLIC KEY-----
         MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvIqz+4+ER/vNWLON9yv8hIYV737JQ6rCl6XfzOC628seYUPf0TaGk91CFxefhzh23V9Tkq+RtwN1Vs/z57hO82kkzL+cQHZX3bMJD+GEGOKXCEXURN7VMyZWMAuzQoW9vFb1k3cR1RW/EW/P+C8bb2dCGXhBYqPfHyimvz2WarXhntPSbM5XyS5v5yCw5T/Vuwqqsio3V8wooWGMpp61y12NhN8bNVDQAkDPNu2DT9DXB1g0CeFINp/KAS/qQ2Kq6TSvRHJqxRR68RezYtje9KAqwqx4jxlmVAQy0T3+T+IAbsk1wRtWDndhO6s1Os+dck5TzyZ/dNOhfXgelixLUQIDAQAB
         -----END PUBLIC KEY-----
        id: 'http://mattiasnkuai.onmicrosoft.com/spring'
        serviceId: 'http://mattiasnkuai.onmicrosoft.com/spring'

